### ISSUE TITLE
How do I wire my Codebug to my Raspberry Pi?

### ISSUE THREAD

**Issue by DougieLawson** [codebugtools/codebug_i2c_tether#1]
I can see how the code gets installed, I can get the cbg file installed on my Codebug all from my Raspberry Pi. But, the missing piece is how to wire RPi pins #3 (SDA), #5 (SCL) & #6 (GND) to my Codebug. 

I've got the same issue with your serial tethering.

**Comment by tompreston** [comment]
After you've installed the cbg file plug CodeBug into the left-most inside row of GPIO pins so that CodeBug is facing inwards. Here's a diagram:

```
+-------------------------------------------------------+
| oooooooooooooooooooooooooooooooooooooooo <- GPIO pins |
| XXXXXXoooooooooooooooooooooooooooooooooo              |
|    ^                                                  |
|    |                                                  |
| CodeBug                                               |
|                                                       |
|                                                       |
|                             RPi                       |
|                                                       |
|                                                       |
|                                                       |
+-------------------------------------------------------+
```

And here's a picture: https://twitter.com/tommarkpreston/status/618737415302328320

I hope that helps.

**Comment by DougieLawson** [comment]
Thank you. I've got it working. I like your hardware solution. 

Is it possible to turn it round in a "left-handed" version of the firmware so that the display on the Codebug is on the outside of the Raspberry Pi? By reversing pins 1-6 on the Codebug.

Can you publish the source code for the firmware piece?

**Comment by tompreston** [comment]
Thanks. 

CodeBug wouldn't fit that way. Our extension pin layout conveniently fits the Raspberry Pi in this application but, ultimately, if you want to do something more complicated (like change the direction of CodeBug or build it into a case etc) then you'll have to use jumper wires.

We're not releasing the source code for the firmware at this time.

**Comment by DougieLawson** [comment]
OK. I found the really teeny tiny printing on the expansion header with my magnifying glass. I'll use some Dupont wires to turn the Codebug round.
